version: '3.1'

volumes:
    logs:
        driver: local

services:
    slim:
        build: .
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        depends_on:
          - mysql
        ports:
            - 80:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        links:
          - mysql

    mysql:
       image: mysql
       restart: always
       container_name: db-mysql
       ports:
        - 3307:3306
       environment:
         MYSQL_DATABASE: paths
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: user
         MYSQL_PASSWORD: pass
       volumes:
        - ./dump:/docker-entrypoint-initdb.d

  
